project_id = "ipoecvfdbndtnezblote"
[functions.get-bus-positions]
enabled = true
verify_jwt = true
import_map = "./functions/get-bus-positions/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-bus-positions/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-bus-positions/*.html" ]
